FROM node:10.21.0

ADD ./mapache-web /usr/src/app

WORKDIR /usr/src/app

COPY ./mapache-web/package*.json /usr/src/app/

# install dependencies
RUN npm install yarn
RUN yarn install
RUN yarn global add react-scripts@3.4.1

# copy the rest of the files
COPY . /usr/src/app/

EXPOSE 3000

CMD ["npm", "dev"]
